CREATE TABLE LIVRARIA (
	NOME_DO_LIVRO VARCHAR (100)PRIMARY KEY,
	NOME_DO_AUTOR VARCHAR(40) NOT NULL,
	SEXO_DO_AUTOR CHAR(1),
	NUMERO_DE_PAGINAS INT ,
	VALOR_DO_LIVRO FLOAT,
	NOME_DA_EDITORA VARCHAR(100),
	ESTADO_UF_DA_EDITORA CHAR(2),
	ANO_PUBLICACAO INT
	);
	
INSERT INTO LIVRARIA (NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NUMERO_DE_PAGINAS,VALOR_DO_LIVRO,NOME_DA_EDITORA,ESTADO_UF_DA_EDITORA,ANO_PUBLICACAO)
VALUE ('CAVALEIRO REAL ','ANA CLAUDIA','F',465,49.9,'ATLAS','RJ',2009);

INSERT INTO LIVRARIA (NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NUMERO_DE_PAGINAS,VALOR_DO_LIVRO,NOME_DA_EDITORA,ESTADO_UF_DA_EDITORA,ANO_PUBLICACAO)
VALUE ('SQL para leigos','João Nunes','M',450,98,'ADDISON','SP',2018);

INSERT INTO LIVRARIA (NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NUMERO_DE_PAGINAS,VALOR_DO_LIVRO,NOME_DA_EDITORA,ESTADO_UF_DA_EDITORA,ANO_PUBLICACAO)
VALUE ('Receitas Caseiras','Celia Tavares','F',210,45,'ATLAS','RJ',2008);

INSERT INTO LIVRARIA (NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NUMERO_DE_PAGINAS,VALOR_DO_LIVRO,NOME_DA_EDITORA,ESTADO_UF_DA_EDITORA,ANO_PUBLICACAO)
VALUE ('Pessoas Efetivas','Eduardo Santos','M',390,78.99,'BETA','RJ',2018);

INSERT INTO LIVRARIA (NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NUMERO_DE_PAGINAS,VALOR_DO_LIVRO,NOME_DA_EDITORA,ESTADO_UF_DA_EDITORA,ANO_PUBLICACAO)
VALUE ('Habitos Saudáveis','Eduardo Santos','M',630,150.98,'BETA','RJ',2019);

INSERT INTO LIVRARIA (NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NUMERO_DE_PAGINAS,VALOR_DO_LIVRO,NOME_DA_EDITORA,ESTADO_UF_DA_EDITORA,ANO_PUBLICACAO)
VALUE ('A Casa Marrom','Hermes Macedo','M',250,60,'BUBBA','MG',2016);

INSERT INTO LIVRARIA (NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NUMERO_DE_PAGINAS,VALOR_DO_LIVRO,NOME_DA_EDITORA,ESTADO_UF_DA_EDITORA,ANO_PUBLICACAO)
VALUE ('Estacio Querido','Geraldo Francisco','M',310,100,'INSIGNIA','ES',2015);

INSERT INTO LIVRARIA (NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NUMERO_DE_PAGINAS,VALOR_DO_LIVRO,NOME_DA_EDITORA,ESTADO_UF_DA_EDITORA,ANO_PUBLICACAO)
VALUE ('Pra sempre amigas','Leda Silva','F',510,78.98,'INSIGNIA','ES',2011);

INSERT INTO LIVRARIA (NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NUMERO_DE_PAGINAS,VALOR_DO_LIVRO,NOME_DA_EDITORA,ESTADO_UF_DA_EDITORA,ANO_PUBLICACAO)
VALUE ('Copas Inesqueciveis','Marco Alcantara','M',200,130.98,'LARSON','RS',2018);

INSERT INTO LIVRARIA (NOME_DO_LIVRO,NOME_DO_AUTOR,SEXO_DO_AUTOR,NUMERO_DE_PAGINAS,VALOR_DO_LIVRO,NOME_DA_EDITORA,ESTADO_UF_DA_EDITORA,ANO_PUBLICACAO)
VALUE ('O poder da mente','Clara Mafra','F',120,56.58,'CONTINENTAL','SP',2017);


/*1 – Trazer todos os dados. */

SELECT * FROM LIVRARIA;

/*2 – Trazer o nome do livro e o nome da editora */

SELECT NOME_DO_AUTOR,NOME_DA_EDITORA FROM LIVRARIA;

/* Trazer o nome do livro e a UF dos livros publicados por autores do sexo masculino*/

SELECT NOME_DO_LIVRO,ESTADO_UF_DA_EDITORA FROM LIVRARIA
WHERE SEXO_DO_AUTOR LIKE '%M';

/*4 - Trazer o nome do livro e o número de páginas dos livros publicados por autores do sexo feminino. */
SELECT NOME_DO_LIVRO,NUMERO_DE_PAGINAS FROM LIVRARIA
WHERE SEXO_DO_AUTOR LIKE '%F';

/*Trazer os valores dos livros das editoras de São Paulo.*/
SELECT VALOR_DO_LIVRO FROM LIVRARIA
WHERE ESTADO_UF_DA_EDITORA LIKE '%SP';

/*Trazer os dados dos autores do sexo masculino que tiveram livros publicados por São Paulo ou Rio de Janeiro (Questão Desafio).*/
/*TENTEI MAS NN DEU CERTO */
SELECT NOME_DO_AUTOR,NOME_DO_LIVRO FROM LIVRARIA 
WHERE SEXO_DO_AUTOR LIKE '%M' AND ESTADO_UF_DA_EDITORA LIKE '%SP' AND ESTADO_UF_DA_EDITORA LIKE '%RJ';




/*ULTIMA QUESTAO CRIADA */

CREATE TABLE CLIENTE (
	NOME VARCHAR (40) NOT NULL,
	ENDERECO VARCHAR (100)NOT NULL,
	TELEFONE VARCHAR (20)
	);
	
INSERT INTO CLIENTE (NOME,ENDERECO,TELEFONE)
VALUES ('IGOR SILVA BRANCO','RUA DOS CHAGAS','SEM TELEFONE ');